// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "@joelek/ts-autoguard/dist/lib-client";
import * as shared from "./index";

export const makeClient = (clientOptions?: autoguard.api.MakeClientOptions): autoguard.api.Client<shared.Autoguard.Requests, shared.Autoguard.Responses> => ({
	"search": async (request) => {
		let guard = shared.Autoguard.Requests["search"];
		guard.as(request, "request");
		let method = "GET";
		let components = new Array<string>();
		components.push("search");
		let parameters = new Array<[string, string]>();
		parameters.push(...autoguard.api.encodeParameterPairs("countryCode", [request.options?.["countryCode"]], true));
		parameters.push(...autoguard.api.encodeParameterPairs("query", [request.options?.["query"]], true));
		parameters.push(...autoguard.api.encodeParameterPairs("offset", [request.options?.["offset"]], false));
		parameters.push(...autoguard.api.encodeParameterPairs("limit", [request.options?.["limit"]], false));
		parameters.push(...autoguard.api.encodeParameterPairs("types", request.options?.["types"] ?? [], true));
		parameters.push(...autoguard.api.encodeParameterPairs("includeContributors", [request.options?.["includeContributors"]], false));
		parameters.push(...autoguard.api.encodeUndeclaredParameterPairs(request.options ?? {}, [...[], ...parameters.map((parameter) => parameter[0])]));
		let headers = new Array<[string, string]>();
		headers.push(...autoguard.api.encodeHeaderPairs("x-tidal-token", [request.headers?.["x-tidal-token"]], true));
		headers.push(...autoguard.api.encodeUndeclaredHeaderPairs(request.headers ?? {}, headers.map((header) => header[0])));
		let payload = request.payload ?? [];
		let requestHandler = clientOptions?.requestHandler ?? autoguard.api.xhr;
		let defaultHeaders = clientOptions?.defaultHeaders?.slice() ?? [];
		defaultHeaders.push(["Content-Type", "application/octet-stream"]);
		defaultHeaders.push(["Accept", "application/json; charset=utf-8"]);
		let raw = await requestHandler(autoguard.api.finalizeRequest({ method, components, parameters, headers, payload }, defaultHeaders), clientOptions?.urlPrefix);
		{
			let status = raw.status;
			let headers: Record<string, autoguard.api.JSON> = {};
			headers = { ...headers, ...autoguard.api.decodeUndeclaredHeaders(raw.headers, Object.keys(headers)) };
			let payload = await autoguard.api.deserializePayload(raw.payload);
			let guard = shared.Autoguard.Responses["search"];
			let response = guard.as({ status, headers, payload }, "response");
			return new autoguard.api.ServerResponse(response, false);
		}
	},
	"getArtist": async (request) => {
		let guard = shared.Autoguard.Requests["getArtist"];
		guard.as(request, "request");
		let method = "GET";
		let components = new Array<string>();
		components.push("artists");
		components.push(...autoguard.api.encodeComponents([request.options?.["id"]], false));
		let parameters = new Array<[string, string]>();
		parameters.push(...autoguard.api.encodeParameterPairs("countryCode", [request.options?.["countryCode"]], true));
		parameters.push(...autoguard.api.encodeUndeclaredParameterPairs(request.options ?? {}, [...["id"], ...parameters.map((parameter) => parameter[0])]));
		let headers = new Array<[string, string]>();
		headers.push(...autoguard.api.encodeHeaderPairs("x-tidal-token", [request.headers?.["x-tidal-token"]], true));
		headers.push(...autoguard.api.encodeUndeclaredHeaderPairs(request.headers ?? {}, headers.map((header) => header[0])));
		let payload = request.payload ?? [];
		let requestHandler = clientOptions?.requestHandler ?? autoguard.api.xhr;
		let defaultHeaders = clientOptions?.defaultHeaders?.slice() ?? [];
		defaultHeaders.push(["Content-Type", "application/octet-stream"]);
		defaultHeaders.push(["Accept", "application/json; charset=utf-8"]);
		let raw = await requestHandler(autoguard.api.finalizeRequest({ method, components, parameters, headers, payload }, defaultHeaders), clientOptions?.urlPrefix);
		{
			let status = raw.status;
			let headers: Record<string, autoguard.api.JSON> = {};
			headers = { ...headers, ...autoguard.api.decodeUndeclaredHeaders(raw.headers, Object.keys(headers)) };
			let payload = await autoguard.api.deserializePayload(raw.payload);
			let guard = shared.Autoguard.Responses["getArtist"];
			let response = guard.as({ status, headers, payload }, "response");
			return new autoguard.api.ServerResponse(response, false);
		}
	},
	"getAlbum": async (request) => {
		let guard = shared.Autoguard.Requests["getAlbum"];
		guard.as(request, "request");
		let method = "GET";
		let components = new Array<string>();
		components.push("albums");
		components.push(...autoguard.api.encodeComponents([request.options?.["id"]], false));
		let parameters = new Array<[string, string]>();
		parameters.push(...autoguard.api.encodeParameterPairs("countryCode", [request.options?.["countryCode"]], true));
		parameters.push(...autoguard.api.encodeUndeclaredParameterPairs(request.options ?? {}, [...["id"], ...parameters.map((parameter) => parameter[0])]));
		let headers = new Array<[string, string]>();
		headers.push(...autoguard.api.encodeHeaderPairs("x-tidal-token", [request.headers?.["x-tidal-token"]], true));
		headers.push(...autoguard.api.encodeUndeclaredHeaderPairs(request.headers ?? {}, headers.map((header) => header[0])));
		let payload = request.payload ?? [];
		let requestHandler = clientOptions?.requestHandler ?? autoguard.api.xhr;
		let defaultHeaders = clientOptions?.defaultHeaders?.slice() ?? [];
		defaultHeaders.push(["Content-Type", "application/octet-stream"]);
		defaultHeaders.push(["Accept", "application/json; charset=utf-8"]);
		let raw = await requestHandler(autoguard.api.finalizeRequest({ method, components, parameters, headers, payload }, defaultHeaders), clientOptions?.urlPrefix);
		{
			let status = raw.status;
			let headers: Record<string, autoguard.api.JSON> = {};
			headers = { ...headers, ...autoguard.api.decodeUndeclaredHeaders(raw.headers, Object.keys(headers)) };
			let payload = await autoguard.api.deserializePayload(raw.payload);
			let guard = shared.Autoguard.Responses["getAlbum"];
			let response = guard.as({ status, headers, payload }, "response");
			return new autoguard.api.ServerResponse(response, false);
		}
	},
});
