// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import { guards as autoguard } from "@joelek/ts-autoguard";

export type Movie = {
	"id": string,
	"title": string,
	"year": number,
	"summary": string,
	"poster_url": string,
	"genres": string[],
	"actors": string[]
};

export const Movie = autoguard.Object.of({
	"id": autoguard.String,
	"title": autoguard.String,
	"year": autoguard.Number,
	"summary": autoguard.String,
	"poster_url": autoguard.String,
	"genres": autoguard.Array.of(autoguard.String),
	"actors": autoguard.Array.of(autoguard.String)
});

export type Show = {
	"id": string,
	"title": string,
	"summary": string,
	"genres": string[],
	"actors": string[]
};

export const Show = autoguard.Object.of({
	"id": autoguard.String,
	"title": autoguard.String,
	"summary": autoguard.String,
	"genres": autoguard.Array.of(autoguard.String),
	"actors": autoguard.Array.of(autoguard.String)
});

export type Episode = {
	"id": string,
	"title": string,
	"air_date": number,
	"summary": string,
	"show_id": string,
	"season": number,
	"episode": number
};

export const Episode = autoguard.Object.of({
	"id": autoguard.String,
	"title": autoguard.String,
	"air_date": autoguard.Number,
	"summary": autoguard.String,
	"show_id": autoguard.String,
	"season": autoguard.Number,
	"episode": autoguard.Number
});

export type Database = {
	"movies": Movie[],
	"shows": Show[],
	"episodes": Episode[]
};

export const Database = autoguard.Object.of({
	"movies": autoguard.Array.of(Movie),
	"shows": autoguard.Array.of(Show),
	"episodes": autoguard.Array.of(Episode)
});

export type Autoguard = {
	"Movie": Movie,
	"Show": Show,
	"Episode": Episode,
	"Database": Database
};

export const Autoguard = {
	"Movie": Movie,
	"Show": Show,
	"Episode": Episode,
	"Database": Database
};
