// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

export type ArtistType = ("ARTIST" | "CONTRIBUTOR" | string);

export const ArtistType = {
	as(subject: any, path: string = ""): ArtistType {
		return ((subject, path) => {
			try {
				return ((subject, path) => {
					if (subject === "ARTIST") {
						return subject;
					}
					throw "Expected \"ARTIST\" at " + path + "!";
				})(subject, path);
			} catch (error) {}
			try {
				return ((subject, path) => {
					if (subject === "CONTRIBUTOR") {
						return subject;
					}
					throw "Expected \"CONTRIBUTOR\" at " + path + "!";
				})(subject, path);
			} catch (error) {}
			try {
				return ((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject, path);
			} catch (error) {}
			throw "Expected a union at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is ArtistType {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type SearchResponseArtist = {
	"id": number,
	"name": string,
	"artistTypes": ArtistType[],
	"url": string,
	"picture": string,
	"popularity": number
};

export const SearchResponseArtist = {
	as(subject: any, path: string = ""): SearchResponseArtist {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["id"], path + "[\"id\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["name"], path + "[\"name\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Array)) {
						for (let i = 0; i < subject.length; i++) {
							(ArtistType.as)(subject[i], path + "[" + i + "]");
						}
						return subject;
					}
					throw "Expected an array at " + path + "!";
				})(subject["artistTypes"], path + "[\"artistTypes\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["url"], path + "[\"url\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["picture"], path + "[\"picture\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["popularity"], path + "[\"popularity\"]");
				return subject;
			}
			throw "Expected an object at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is SearchResponseArtist {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type AlbumType = ("ALBUM" | string);

export const AlbumType = {
	as(subject: any, path: string = ""): AlbumType {
		return ((subject, path) => {
			try {
				return ((subject, path) => {
					if (subject === "ALBUM") {
						return subject;
					}
					throw "Expected \"ALBUM\" at " + path + "!";
				})(subject, path);
			} catch (error) {}
			try {
				return ((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject, path);
			} catch (error) {}
			throw "Expected a union at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is AlbumType {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type AudioQualityType = ("LOSSLESS" | "HI_RES" | string);

export const AudioQualityType = {
	as(subject: any, path: string = ""): AudioQualityType {
		return ((subject, path) => {
			try {
				return ((subject, path) => {
					if (subject === "LOSSLESS") {
						return subject;
					}
					throw "Expected \"LOSSLESS\" at " + path + "!";
				})(subject, path);
			} catch (error) {}
			try {
				return ((subject, path) => {
					if (subject === "HI_RES") {
						return subject;
					}
					throw "Expected \"HI_RES\" at " + path + "!";
				})(subject, path);
			} catch (error) {}
			try {
				return ((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject, path);
			} catch (error) {}
			throw "Expected a union at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is AudioQualityType {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type AudioModeType = ("STEREO" | string);

export const AudioModeType = {
	as(subject: any, path: string = ""): AudioModeType {
		return ((subject, path) => {
			try {
				return ((subject, path) => {
					if (subject === "STEREO") {
						return subject;
					}
					throw "Expected \"STEREO\" at " + path + "!";
				})(subject, path);
			} catch (error) {}
			try {
				return ((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject, path);
			} catch (error) {}
			throw "Expected a union at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is AudioModeType {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type ArtistRelationType = ("MAIN" | "FEATURED" | string);

export const ArtistRelationType = {
	as(subject: any, path: string = ""): ArtistRelationType {
		return ((subject, path) => {
			try {
				return ((subject, path) => {
					if (subject === "MAIN") {
						return subject;
					}
					throw "Expected \"MAIN\" at " + path + "!";
				})(subject, path);
			} catch (error) {}
			try {
				return ((subject, path) => {
					if (subject === "FEATURED") {
						return subject;
					}
					throw "Expected \"FEATURED\" at " + path + "!";
				})(subject, path);
			} catch (error) {}
			try {
				return ((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject, path);
			} catch (error) {}
			throw "Expected a union at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is ArtistRelationType {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type SearchResponseArtistRelation = {
	"id": number,
	"name": string,
	"type": ArtistRelationType
};

export const SearchResponseArtistRelation = {
	as(subject: any, path: string = ""): SearchResponseArtistRelation {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["id"], path + "[\"id\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["name"], path + "[\"name\"]");
				(ArtistRelationType.as)(subject["type"], path + "[\"type\"]");
				return subject;
			}
			throw "Expected an object at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is SearchResponseArtistRelation {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type AlbumRelation = {
	"id": number,
	"title": string,
	"cover": string,
	"videoCover": (null | any),
	"releaseDate": string
};

export const AlbumRelation = {
	as(subject: any, path: string = ""): AlbumRelation {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["id"], path + "[\"id\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["title"], path + "[\"title\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["cover"], path + "[\"cover\"]");
				((subject, path) => {
					try {
						return ((subject, path) => {
							if (subject === null) {
								return subject;
							}
							throw "Expected null at " + path + "!";
						})(subject, path);
					} catch (error) {}
					try {
						return ((subject, path) => {
							return subject;
						})(subject, path);
					} catch (error) {}
					throw "Expected a union at " + path + "!";
				})(subject["videoCover"], path + "[\"videoCover\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["releaseDate"], path + "[\"releaseDate\"]");
				return subject;
			}
			throw "Expected an object at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is AlbumRelation {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type SearchResponseAlbum = {
	"id": number,
	"title": string,
	"duration": number,
	"streamReady": boolean,
	"streamStartDate": string,
	"allowStreaming": boolean,
	"premiumStreamingOnly": boolean,
	"numberOfTracks": number,
	"numberOfVideos": number,
	"numberOfVolumes": number,
	"releaseDate": string,
	"copyright": string,
	"type": AlbumType,
	"version": (any | null),
	"url": string,
	"cover": string,
	"videoCover": (any | null),
	"explicit": boolean,
	"upc": string,
	"popularity": number,
	"audioQuality": AudioQualityType,
	"audioModes": AudioModeType[],
	"artists": SearchResponseArtistRelation[]
};

export const SearchResponseAlbum = {
	as(subject: any, path: string = ""): SearchResponseAlbum {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["id"], path + "[\"id\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["title"], path + "[\"title\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["duration"], path + "[\"duration\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Boolean)) {
						return subject as boolean;
					}
					throw "Expected a boolean at " + path + "!";
				})(subject["streamReady"], path + "[\"streamReady\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["streamStartDate"], path + "[\"streamStartDate\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Boolean)) {
						return subject as boolean;
					}
					throw "Expected a boolean at " + path + "!";
				})(subject["allowStreaming"], path + "[\"allowStreaming\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Boolean)) {
						return subject as boolean;
					}
					throw "Expected a boolean at " + path + "!";
				})(subject["premiumStreamingOnly"], path + "[\"premiumStreamingOnly\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["numberOfTracks"], path + "[\"numberOfTracks\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["numberOfVideos"], path + "[\"numberOfVideos\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["numberOfVolumes"], path + "[\"numberOfVolumes\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["releaseDate"], path + "[\"releaseDate\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["copyright"], path + "[\"copyright\"]");
				(AlbumType.as)(subject["type"], path + "[\"type\"]");
				((subject, path) => {
					try {
						return ((subject, path) => {
							return subject;
						})(subject, path);
					} catch (error) {}
					try {
						return ((subject, path) => {
							if (subject === null) {
								return subject;
							}
							throw "Expected null at " + path + "!";
						})(subject, path);
					} catch (error) {}
					throw "Expected a union at " + path + "!";
				})(subject["version"], path + "[\"version\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["url"], path + "[\"url\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["cover"], path + "[\"cover\"]");
				((subject, path) => {
					try {
						return ((subject, path) => {
							return subject;
						})(subject, path);
					} catch (error) {}
					try {
						return ((subject, path) => {
							if (subject === null) {
								return subject;
							}
							throw "Expected null at " + path + "!";
						})(subject, path);
					} catch (error) {}
					throw "Expected a union at " + path + "!";
				})(subject["videoCover"], path + "[\"videoCover\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Boolean)) {
						return subject as boolean;
					}
					throw "Expected a boolean at " + path + "!";
				})(subject["explicit"], path + "[\"explicit\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["upc"], path + "[\"upc\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["popularity"], path + "[\"popularity\"]");
				(AudioQualityType.as)(subject["audioQuality"], path + "[\"audioQuality\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Array)) {
						for (let i = 0; i < subject.length; i++) {
							(AudioModeType.as)(subject[i], path + "[" + i + "]");
						}
						return subject;
					}
					throw "Expected an array at " + path + "!";
				})(subject["audioModes"], path + "[\"audioModes\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Array)) {
						for (let i = 0; i < subject.length; i++) {
							(SearchResponseArtistRelation.as)(subject[i], path + "[" + i + "]");
						}
						return subject;
					}
					throw "Expected an array at " + path + "!";
				})(subject["artists"], path + "[\"artists\"]");
				return subject;
			}
			throw "Expected an object at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is SearchResponseAlbum {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type PlaylistType = ("ARTIST" | "EDITORIAL" | string);

export const PlaylistType = {
	as(subject: any, path: string = ""): PlaylistType {
		return ((subject, path) => {
			try {
				return ((subject, path) => {
					if (subject === "ARTIST") {
						return subject;
					}
					throw "Expected \"ARTIST\" at " + path + "!";
				})(subject, path);
			} catch (error) {}
			try {
				return ((subject, path) => {
					if (subject === "EDITORIAL") {
						return subject;
					}
					throw "Expected \"EDITORIAL\" at " + path + "!";
				})(subject, path);
			} catch (error) {}
			try {
				return ((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject, path);
			} catch (error) {}
			throw "Expected a union at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is PlaylistType {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type PlaylistCreator = {
	"id": number,
	"name": string,
	"artistTypes": (null | any),
	"url": (null | any),
	"picture": (null | any),
	"popularity": number
};

export const PlaylistCreator = {
	as(subject: any, path: string = ""): PlaylistCreator {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["id"], path + "[\"id\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["name"], path + "[\"name\"]");
				((subject, path) => {
					try {
						return ((subject, path) => {
							if (subject === null) {
								return subject;
							}
							throw "Expected null at " + path + "!";
						})(subject, path);
					} catch (error) {}
					try {
						return ((subject, path) => {
							return subject;
						})(subject, path);
					} catch (error) {}
					throw "Expected a union at " + path + "!";
				})(subject["artistTypes"], path + "[\"artistTypes\"]");
				((subject, path) => {
					try {
						return ((subject, path) => {
							if (subject === null) {
								return subject;
							}
							throw "Expected null at " + path + "!";
						})(subject, path);
					} catch (error) {}
					try {
						return ((subject, path) => {
							return subject;
						})(subject, path);
					} catch (error) {}
					throw "Expected a union at " + path + "!";
				})(subject["url"], path + "[\"url\"]");
				((subject, path) => {
					try {
						return ((subject, path) => {
							if (subject === null) {
								return subject;
							}
							throw "Expected null at " + path + "!";
						})(subject, path);
					} catch (error) {}
					try {
						return ((subject, path) => {
							return subject;
						})(subject, path);
					} catch (error) {}
					throw "Expected a union at " + path + "!";
				})(subject["picture"], path + "[\"picture\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["popularity"], path + "[\"popularity\"]");
				return subject;
			}
			throw "Expected an object at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is PlaylistCreator {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type SearchResponsePlaylist = {
	"uuid": string,
	"title": string,
	"numberOfTracks": number,
	"numberOfVideos": number,
	"creator": ({} | PlaylistCreator),
	"description": string,
	"duration": number,
	"lastUpdated": string,
	"created": string,
	"type": PlaylistType,
	"publicPlaylist": boolean,
	"url": string,
	"image": string,
	"popularity": number,
	"squareImage": string,
	"promotedArtists": SearchResponseArtistRelation[],
	"lastItemAddedAt": (null | any)
};

export const SearchResponsePlaylist = {
	as(subject: any, path: string = ""): SearchResponsePlaylist {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["uuid"], path + "[\"uuid\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["title"], path + "[\"title\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["numberOfTracks"], path + "[\"numberOfTracks\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["numberOfVideos"], path + "[\"numberOfVideos\"]");
				((subject, path) => {
					try {
						return ((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Object)) {
								return subject;
							}
							throw "Expected an object at " + path + "!";
						})(subject, path);
					} catch (error) {}
					try {
						return (PlaylistCreator.as)(subject, path);
					} catch (error) {}
					throw "Expected a union at " + path + "!";
				})(subject["creator"], path + "[\"creator\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["description"], path + "[\"description\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["duration"], path + "[\"duration\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["lastUpdated"], path + "[\"lastUpdated\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["created"], path + "[\"created\"]");
				(PlaylistType.as)(subject["type"], path + "[\"type\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Boolean)) {
						return subject as boolean;
					}
					throw "Expected a boolean at " + path + "!";
				})(subject["publicPlaylist"], path + "[\"publicPlaylist\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["url"], path + "[\"url\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["image"], path + "[\"image\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["popularity"], path + "[\"popularity\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["squareImage"], path + "[\"squareImage\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Array)) {
						for (let i = 0; i < subject.length; i++) {
							(SearchResponseArtistRelation.as)(subject[i], path + "[" + i + "]");
						}
						return subject;
					}
					throw "Expected an array at " + path + "!";
				})(subject["promotedArtists"], path + "[\"promotedArtists\"]");
				((subject, path) => {
					try {
						return ((subject, path) => {
							if (subject === null) {
								return subject;
							}
							throw "Expected null at " + path + "!";
						})(subject, path);
					} catch (error) {}
					try {
						return ((subject, path) => {
							return subject;
						})(subject, path);
					} catch (error) {}
					throw "Expected a union at " + path + "!";
				})(subject["lastItemAddedAt"], path + "[\"lastItemAddedAt\"]");
				return subject;
			}
			throw "Expected an object at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is SearchResponsePlaylist {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type SearchResponseTrack = {
	"id": number,
	"title": string,
	"duration": number,
	"replayGain": number,
	"peak": number,
	"allowStreaming": boolean,
	"streamReady": boolean,
	"streamStartDate": string,
	"premiumStreamingOnly": boolean,
	"trackNumber": number,
	"volumeNumber": number,
	"version": (null | any),
	"popularity": number,
	"copyright": string,
	"url": string,
	"isrc": string,
	"editable": boolean,
	"explicit": boolean,
	"audioQuality": AudioQualityType,
	"audioModes": AudioModeType[],
	"artists": SearchResponseArtistRelation[],
	"album": AlbumRelation
};

export const SearchResponseTrack = {
	as(subject: any, path: string = ""): SearchResponseTrack {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["id"], path + "[\"id\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["title"], path + "[\"title\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["duration"], path + "[\"duration\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["replayGain"], path + "[\"replayGain\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["peak"], path + "[\"peak\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Boolean)) {
						return subject as boolean;
					}
					throw "Expected a boolean at " + path + "!";
				})(subject["allowStreaming"], path + "[\"allowStreaming\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Boolean)) {
						return subject as boolean;
					}
					throw "Expected a boolean at " + path + "!";
				})(subject["streamReady"], path + "[\"streamReady\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["streamStartDate"], path + "[\"streamStartDate\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Boolean)) {
						return subject as boolean;
					}
					throw "Expected a boolean at " + path + "!";
				})(subject["premiumStreamingOnly"], path + "[\"premiumStreamingOnly\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["trackNumber"], path + "[\"trackNumber\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["volumeNumber"], path + "[\"volumeNumber\"]");
				((subject, path) => {
					try {
						return ((subject, path) => {
							if (subject === null) {
								return subject;
							}
							throw "Expected null at " + path + "!";
						})(subject, path);
					} catch (error) {}
					try {
						return ((subject, path) => {
							return subject;
						})(subject, path);
					} catch (error) {}
					throw "Expected a union at " + path + "!";
				})(subject["version"], path + "[\"version\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["popularity"], path + "[\"popularity\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["copyright"], path + "[\"copyright\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["url"], path + "[\"url\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["isrc"], path + "[\"isrc\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Boolean)) {
						return subject as boolean;
					}
					throw "Expected a boolean at " + path + "!";
				})(subject["editable"], path + "[\"editable\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Boolean)) {
						return subject as boolean;
					}
					throw "Expected a boolean at " + path + "!";
				})(subject["explicit"], path + "[\"explicit\"]");
				(AudioQualityType.as)(subject["audioQuality"], path + "[\"audioQuality\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Array)) {
						for (let i = 0; i < subject.length; i++) {
							(AudioModeType.as)(subject[i], path + "[" + i + "]");
						}
						return subject;
					}
					throw "Expected an array at " + path + "!";
				})(subject["audioModes"], path + "[\"audioModes\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Array)) {
						for (let i = 0; i < subject.length; i++) {
							(SearchResponseArtistRelation.as)(subject[i], path + "[" + i + "]");
						}
						return subject;
					}
					throw "Expected an array at " + path + "!";
				})(subject["artists"], path + "[\"artists\"]");
				(AlbumRelation.as)(subject["album"], path + "[\"album\"]");
				return subject;
			}
			throw "Expected an object at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is SearchResponseTrack {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type SearchResponseVideoQualityType = ("MP4_1080P" | string);

export const SearchResponseVideoQualityType = {
	as(subject: any, path: string = ""): SearchResponseVideoQualityType {
		return ((subject, path) => {
			try {
				return ((subject, path) => {
					if (subject === "MP4_1080P") {
						return subject;
					}
					throw "Expected \"MP4_1080P\" at " + path + "!";
				})(subject, path);
			} catch (error) {}
			try {
				return ((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject, path);
			} catch (error) {}
			throw "Expected a union at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is SearchResponseVideoQualityType {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type SearchResponseVideo = {
	"id": number,
	"title": string,
	"volumeNumber": number,
	"trackNumber": number,
	"releaseDate": string,
	"imagePath": (null | any),
	"imageId": string,
	"duration": number,
	"quality": SearchResponseVideoQualityType,
	"streamReady": boolean,
	"streamStartDate": string,
	"allowStreaming": boolean,
	"explicit": boolean,
	"popularity": number,
	"type": string,
	"adsUrl": (null | any),
	"adsPrePaywallOnly": boolean,
	"artists": SearchResponseArtistRelation[],
	"album": (null | any)
};

export const SearchResponseVideo = {
	as(subject: any, path: string = ""): SearchResponseVideo {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["id"], path + "[\"id\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["title"], path + "[\"title\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["volumeNumber"], path + "[\"volumeNumber\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["trackNumber"], path + "[\"trackNumber\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["releaseDate"], path + "[\"releaseDate\"]");
				((subject, path) => {
					try {
						return ((subject, path) => {
							if (subject === null) {
								return subject;
							}
							throw "Expected null at " + path + "!";
						})(subject, path);
					} catch (error) {}
					try {
						return ((subject, path) => {
							return subject;
						})(subject, path);
					} catch (error) {}
					throw "Expected a union at " + path + "!";
				})(subject["imagePath"], path + "[\"imagePath\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["imageId"], path + "[\"imageId\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["duration"], path + "[\"duration\"]");
				(SearchResponseVideoQualityType.as)(subject["quality"], path + "[\"quality\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Boolean)) {
						return subject as boolean;
					}
					throw "Expected a boolean at " + path + "!";
				})(subject["streamReady"], path + "[\"streamReady\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["streamStartDate"], path + "[\"streamStartDate\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Boolean)) {
						return subject as boolean;
					}
					throw "Expected a boolean at " + path + "!";
				})(subject["allowStreaming"], path + "[\"allowStreaming\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Boolean)) {
						return subject as boolean;
					}
					throw "Expected a boolean at " + path + "!";
				})(subject["explicit"], path + "[\"explicit\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Number)) {
						return subject as number;
					}
					throw "Expected a number at " + path + "!";
				})(subject["popularity"], path + "[\"popularity\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["type"], path + "[\"type\"]");
				((subject, path) => {
					try {
						return ((subject, path) => {
							if (subject === null) {
								return subject;
							}
							throw "Expected null at " + path + "!";
						})(subject, path);
					} catch (error) {}
					try {
						return ((subject, path) => {
							return subject;
						})(subject, path);
					} catch (error) {}
					throw "Expected a union at " + path + "!";
				})(subject["adsUrl"], path + "[\"adsUrl\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Boolean)) {
						return subject as boolean;
					}
					throw "Expected a boolean at " + path + "!";
				})(subject["adsPrePaywallOnly"], path + "[\"adsPrePaywallOnly\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Array)) {
						for (let i = 0; i < subject.length; i++) {
							(SearchResponseArtistRelation.as)(subject[i], path + "[" + i + "]");
						}
						return subject;
					}
					throw "Expected an array at " + path + "!";
				})(subject["artists"], path + "[\"artists\"]");
				((subject, path) => {
					try {
						return ((subject, path) => {
							if (subject === null) {
								return subject;
							}
							throw "Expected null at " + path + "!";
						})(subject, path);
					} catch (error) {}
					try {
						return ((subject, path) => {
							return subject;
						})(subject, path);
					} catch (error) {}
					throw "Expected a union at " + path + "!";
				})(subject["album"], path + "[\"album\"]");
				return subject;
			}
			throw "Expected an object at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is SearchResponseVideo {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type EntityType = ("ARTISTS" | "ALBUMS" | "PLAYLISTS" | "TRACKS" | "VIDEOS");

export const EntityType = {
	as(subject: any, path: string = ""): EntityType {
		return ((subject, path) => {
			try {
				return ((subject, path) => {
					if (subject === "ARTISTS") {
						return subject;
					}
					throw "Expected \"ARTISTS\" at " + path + "!";
				})(subject, path);
			} catch (error) {}
			try {
				return ((subject, path) => {
					if (subject === "ALBUMS") {
						return subject;
					}
					throw "Expected \"ALBUMS\" at " + path + "!";
				})(subject, path);
			} catch (error) {}
			try {
				return ((subject, path) => {
					if (subject === "PLAYLISTS") {
						return subject;
					}
					throw "Expected \"PLAYLISTS\" at " + path + "!";
				})(subject, path);
			} catch (error) {}
			try {
				return ((subject, path) => {
					if (subject === "TRACKS") {
						return subject;
					}
					throw "Expected \"TRACKS\" at " + path + "!";
				})(subject, path);
			} catch (error) {}
			try {
				return ((subject, path) => {
					if (subject === "VIDEOS") {
						return subject;
					}
					throw "Expected \"VIDEOS\" at " + path + "!";
				})(subject, path);
			} catch (error) {}
			throw "Expected a union at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is EntityType {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type SearchResponseTopHitArtist = {
	"value": SearchResponseArtist,
	"type": "ARTISTS"
};

export const SearchResponseTopHitArtist = {
	as(subject: any, path: string = ""): SearchResponseTopHitArtist {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				(SearchResponseArtist.as)(subject["value"], path + "[\"value\"]");
				((subject, path) => {
					if (subject === "ARTISTS") {
						return subject;
					}
					throw "Expected \"ARTISTS\" at " + path + "!";
				})(subject["type"], path + "[\"type\"]");
				return subject;
			}
			throw "Expected an object at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is SearchResponseTopHitArtist {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type SearchResponseTopHitAlbum = {
	"value": SearchResponseAlbum,
	"type": "ALBUMS"
};

export const SearchResponseTopHitAlbum = {
	as(subject: any, path: string = ""): SearchResponseTopHitAlbum {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				(SearchResponseAlbum.as)(subject["value"], path + "[\"value\"]");
				((subject, path) => {
					if (subject === "ALBUMS") {
						return subject;
					}
					throw "Expected \"ALBUMS\" at " + path + "!";
				})(subject["type"], path + "[\"type\"]");
				return subject;
			}
			throw "Expected an object at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is SearchResponseTopHitAlbum {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type SearchResponseTopHitPlaylist = {
	"value": SearchResponsePlaylist,
	"type": "PLAYLISTS"
};

export const SearchResponseTopHitPlaylist = {
	as(subject: any, path: string = ""): SearchResponseTopHitPlaylist {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				(SearchResponsePlaylist.as)(subject["value"], path + "[\"value\"]");
				((subject, path) => {
					if (subject === "PLAYLISTS") {
						return subject;
					}
					throw "Expected \"PLAYLISTS\" at " + path + "!";
				})(subject["type"], path + "[\"type\"]");
				return subject;
			}
			throw "Expected an object at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is SearchResponseTopHitPlaylist {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type SearchResponseTopHitTrack = {
	"value": SearchResponseTrack,
	"type": "TRACKS"
};

export const SearchResponseTopHitTrack = {
	as(subject: any, path: string = ""): SearchResponseTopHitTrack {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				(SearchResponseTrack.as)(subject["value"], path + "[\"value\"]");
				((subject, path) => {
					if (subject === "TRACKS") {
						return subject;
					}
					throw "Expected \"TRACKS\" at " + path + "!";
				})(subject["type"], path + "[\"type\"]");
				return subject;
			}
			throw "Expected an object at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is SearchResponseTopHitTrack {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type SearchResponseTopHitVideo = {
	"value": SearchResponseVideo,
	"type": "VIDEOS"
};

export const SearchResponseTopHitVideo = {
	as(subject: any, path: string = ""): SearchResponseTopHitVideo {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				(SearchResponseVideo.as)(subject["value"], path + "[\"value\"]");
				((subject, path) => {
					if (subject === "VIDEOS") {
						return subject;
					}
					throw "Expected \"VIDEOS\" at " + path + "!";
				})(subject["type"], path + "[\"type\"]");
				return subject;
			}
			throw "Expected an object at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is SearchResponseTopHitVideo {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type SearchResponse = {
	"artists": {
		"limit": number,
		"offset": number,
		"totalNumberOfItems": number,
		"items": SearchResponseArtist[]
	},
	"albums": {
		"limit": number,
		"offset": number,
		"totalNumberOfItems": number,
		"items": SearchResponseAlbum[]
	},
	"playlists": {
		"limit": number,
		"offset": number,
		"totalNumberOfItems": number,
		"items": SearchResponsePlaylist[]
	},
	"tracks": {
		"limit": number,
		"offset": number,
		"totalNumberOfItems": number,
		"items": SearchResponseTrack[]
	},
	"videos": {
		"limit": number,
		"offset": number,
		"totalNumberOfItems": number,
		"items": SearchResponseVideo[]
	},
	"topHit": (SearchResponseTopHitArtist | SearchResponseTopHitAlbum | SearchResponseTopHitPlaylist | SearchResponseTopHitTrack | SearchResponseTopHitVideo | null)
};

export const SearchResponse = {
	as(subject: any, path: string = ""): SearchResponse {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Object)) {
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Number)) {
								return subject as number;
							}
							throw "Expected a number at " + path + "!";
						})(subject["limit"], path + "[\"limit\"]");
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Number)) {
								return subject as number;
							}
							throw "Expected a number at " + path + "!";
						})(subject["offset"], path + "[\"offset\"]");
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Number)) {
								return subject as number;
							}
							throw "Expected a number at " + path + "!";
						})(subject["totalNumberOfItems"], path + "[\"totalNumberOfItems\"]");
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Array)) {
								for (let i = 0; i < subject.length; i++) {
									(SearchResponseArtist.as)(subject[i], path + "[" + i + "]");
								}
								return subject;
							}
							throw "Expected an array at " + path + "!";
						})(subject["items"], path + "[\"items\"]");
						return subject;
					}
					throw "Expected an object at " + path + "!";
				})(subject["artists"], path + "[\"artists\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Object)) {
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Number)) {
								return subject as number;
							}
							throw "Expected a number at " + path + "!";
						})(subject["limit"], path + "[\"limit\"]");
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Number)) {
								return subject as number;
							}
							throw "Expected a number at " + path + "!";
						})(subject["offset"], path + "[\"offset\"]");
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Number)) {
								return subject as number;
							}
							throw "Expected a number at " + path + "!";
						})(subject["totalNumberOfItems"], path + "[\"totalNumberOfItems\"]");
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Array)) {
								for (let i = 0; i < subject.length; i++) {
									(SearchResponseAlbum.as)(subject[i], path + "[" + i + "]");
								}
								return subject;
							}
							throw "Expected an array at " + path + "!";
						})(subject["items"], path + "[\"items\"]");
						return subject;
					}
					throw "Expected an object at " + path + "!";
				})(subject["albums"], path + "[\"albums\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Object)) {
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Number)) {
								return subject as number;
							}
							throw "Expected a number at " + path + "!";
						})(subject["limit"], path + "[\"limit\"]");
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Number)) {
								return subject as number;
							}
							throw "Expected a number at " + path + "!";
						})(subject["offset"], path + "[\"offset\"]");
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Number)) {
								return subject as number;
							}
							throw "Expected a number at " + path + "!";
						})(subject["totalNumberOfItems"], path + "[\"totalNumberOfItems\"]");
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Array)) {
								for (let i = 0; i < subject.length; i++) {
									(SearchResponsePlaylist.as)(subject[i], path + "[" + i + "]");
								}
								return subject;
							}
							throw "Expected an array at " + path + "!";
						})(subject["items"], path + "[\"items\"]");
						return subject;
					}
					throw "Expected an object at " + path + "!";
				})(subject["playlists"], path + "[\"playlists\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Object)) {
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Number)) {
								return subject as number;
							}
							throw "Expected a number at " + path + "!";
						})(subject["limit"], path + "[\"limit\"]");
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Number)) {
								return subject as number;
							}
							throw "Expected a number at " + path + "!";
						})(subject["offset"], path + "[\"offset\"]");
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Number)) {
								return subject as number;
							}
							throw "Expected a number at " + path + "!";
						})(subject["totalNumberOfItems"], path + "[\"totalNumberOfItems\"]");
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Array)) {
								for (let i = 0; i < subject.length; i++) {
									(SearchResponseTrack.as)(subject[i], path + "[" + i + "]");
								}
								return subject;
							}
							throw "Expected an array at " + path + "!";
						})(subject["items"], path + "[\"items\"]");
						return subject;
					}
					throw "Expected an object at " + path + "!";
				})(subject["tracks"], path + "[\"tracks\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Object)) {
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Number)) {
								return subject as number;
							}
							throw "Expected a number at " + path + "!";
						})(subject["limit"], path + "[\"limit\"]");
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Number)) {
								return subject as number;
							}
							throw "Expected a number at " + path + "!";
						})(subject["offset"], path + "[\"offset\"]");
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Number)) {
								return subject as number;
							}
							throw "Expected a number at " + path + "!";
						})(subject["totalNumberOfItems"], path + "[\"totalNumberOfItems\"]");
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Array)) {
								for (let i = 0; i < subject.length; i++) {
									(SearchResponseVideo.as)(subject[i], path + "[" + i + "]");
								}
								return subject;
							}
							throw "Expected an array at " + path + "!";
						})(subject["items"], path + "[\"items\"]");
						return subject;
					}
					throw "Expected an object at " + path + "!";
				})(subject["videos"], path + "[\"videos\"]");
				((subject, path) => {
					try {
						return (SearchResponseTopHitArtist.as)(subject, path);
					} catch (error) {}
					try {
						return (SearchResponseTopHitAlbum.as)(subject, path);
					} catch (error) {}
					try {
						return (SearchResponseTopHitPlaylist.as)(subject, path);
					} catch (error) {}
					try {
						return (SearchResponseTopHitTrack.as)(subject, path);
					} catch (error) {}
					try {
						return (SearchResponseTopHitVideo.as)(subject, path);
					} catch (error) {}
					try {
						return ((subject, path) => {
							if (subject === null) {
								return subject;
							}
							throw "Expected null at " + path + "!";
						})(subject, path);
					} catch (error) {}
					throw "Expected a union at " + path + "!";
				})(subject["topHit"], path + "[\"topHit\"]");
				return subject;
			}
			throw "Expected an object at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is SearchResponse {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type Autoguard = {
	"ArtistType": ArtistType,
	"SearchResponseArtist": SearchResponseArtist,
	"AlbumType": AlbumType,
	"AudioQualityType": AudioQualityType,
	"AudioModeType": AudioModeType,
	"ArtistRelationType": ArtistRelationType,
	"SearchResponseArtistRelation": SearchResponseArtistRelation,
	"AlbumRelation": AlbumRelation,
	"SearchResponseAlbum": SearchResponseAlbum,
	"PlaylistType": PlaylistType,
	"PlaylistCreator": PlaylistCreator,
	"SearchResponsePlaylist": SearchResponsePlaylist,
	"SearchResponseTrack": SearchResponseTrack,
	"SearchResponseVideoQualityType": SearchResponseVideoQualityType,
	"SearchResponseVideo": SearchResponseVideo,
	"EntityType": EntityType,
	"SearchResponseTopHitArtist": SearchResponseTopHitArtist,
	"SearchResponseTopHitAlbum": SearchResponseTopHitAlbum,
	"SearchResponseTopHitPlaylist": SearchResponseTopHitPlaylist,
	"SearchResponseTopHitTrack": SearchResponseTopHitTrack,
	"SearchResponseTopHitVideo": SearchResponseTopHitVideo,
	"SearchResponse": SearchResponse
};

export const Autoguard = {
	"ArtistType": ArtistType,
	"SearchResponseArtist": SearchResponseArtist,
	"AlbumType": AlbumType,
	"AudioQualityType": AudioQualityType,
	"AudioModeType": AudioModeType,
	"ArtistRelationType": ArtistRelationType,
	"SearchResponseArtistRelation": SearchResponseArtistRelation,
	"AlbumRelation": AlbumRelation,
	"SearchResponseAlbum": SearchResponseAlbum,
	"PlaylistType": PlaylistType,
	"PlaylistCreator": PlaylistCreator,
	"SearchResponsePlaylist": SearchResponsePlaylist,
	"SearchResponseTrack": SearchResponseTrack,
	"SearchResponseVideoQualityType": SearchResponseVideoQualityType,
	"SearchResponseVideo": SearchResponseVideo,
	"EntityType": EntityType,
	"SearchResponseTopHitArtist": SearchResponseTopHitArtist,
	"SearchResponseTopHitAlbum": SearchResponseTopHitAlbum,
	"SearchResponseTopHitPlaylist": SearchResponseTopHitPlaylist,
	"SearchResponseTopHitTrack": SearchResponseTopHitTrack,
	"SearchResponseTopHitVideo": SearchResponseTopHitVideo,
	"SearchResponse": SearchResponse
};
