// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "@joelek/ts-autoguard/dist/lib-shared";

export const Movie: autoguard.serialization.MessageGuard<Movie> = autoguard.guards.Object.of({
	"id": autoguard.guards.String,
	"title": autoguard.guards.String,
	"year": autoguard.guards.Number,
	"summary": autoguard.guards.String,
	"poster_url": autoguard.guards.String,
	"genres": autoguard.guards.Array.of(autoguard.guards.String),
	"actors": autoguard.guards.Array.of(autoguard.guards.String)
}, {});

export type Movie = autoguard.guards.Object<{
	"id": autoguard.guards.String,
	"title": autoguard.guards.String,
	"year": autoguard.guards.Number,
	"summary": autoguard.guards.String,
	"poster_url": autoguard.guards.String,
	"genres": autoguard.guards.Array<autoguard.guards.String>,
	"actors": autoguard.guards.Array<autoguard.guards.String>
}, {}>;

export const Show: autoguard.serialization.MessageGuard<Show> = autoguard.guards.Object.of({
	"id": autoguard.guards.String,
	"title": autoguard.guards.String,
	"summary": autoguard.guards.String,
	"poster_url": autoguard.guards.String,
	"genres": autoguard.guards.Array.of(autoguard.guards.String),
	"actors": autoguard.guards.Array.of(autoguard.guards.String)
}, {});

export type Show = autoguard.guards.Object<{
	"id": autoguard.guards.String,
	"title": autoguard.guards.String,
	"summary": autoguard.guards.String,
	"poster_url": autoguard.guards.String,
	"genres": autoguard.guards.Array<autoguard.guards.String>,
	"actors": autoguard.guards.Array<autoguard.guards.String>
}, {}>;

export const Episode: autoguard.serialization.MessageGuard<Episode> = autoguard.guards.Object.of({
	"id": autoguard.guards.String,
	"title": autoguard.guards.String,
	"air_date": autoguard.guards.Number,
	"summary": autoguard.guards.String,
	"show_id": autoguard.guards.String,
	"season": autoguard.guards.Number,
	"episode": autoguard.guards.Number
}, {});

export type Episode = autoguard.guards.Object<{
	"id": autoguard.guards.String,
	"title": autoguard.guards.String,
	"air_date": autoguard.guards.Number,
	"summary": autoguard.guards.String,
	"show_id": autoguard.guards.String,
	"season": autoguard.guards.Number,
	"episode": autoguard.guards.Number
}, {}>;

export const Database: autoguard.serialization.MessageGuard<Database> = autoguard.guards.Object.of({
	"movies": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Movie)),
	"shows": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Show)),
	"episodes": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Episode))
}, {});

export type Database = autoguard.guards.Object<{
	"movies": autoguard.guards.Array<autoguard.guards.Reference<Movie>>,
	"shows": autoguard.guards.Array<autoguard.guards.Reference<Show>>,
	"episodes": autoguard.guards.Array<autoguard.guards.Reference<Episode>>
}, {}>;

export namespace Autoguard {
	export const Guards = {
		"Movie": autoguard.guards.Reference.of(() => Movie),
		"Show": autoguard.guards.Reference.of(() => Show),
		"Episode": autoguard.guards.Reference.of(() => Episode),
		"Database": autoguard.guards.Reference.of(() => Database)
	};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
