// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

export type DeviceDetails = {
	"vendor_id": string,
	"product_id": string
};

export const DeviceDetails = {
	as(subject: any, path: string = ""): DeviceDetails {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["vendor_id"], path + "[\"vendor_id\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.String)) {
						return subject as string;
					}
					throw "Expected a string at " + path + "!";
				})(subject["product_id"], path + "[\"product_id\"]");
				return subject;
			}
			throw "Expected an object at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is DeviceDetails {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type Autoguard = {
	"DeviceDetails": DeviceDetails
};

export const Autoguard = {
	"DeviceDetails": DeviceDetails
};
