// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import { guards as autoguard } from "@joelek/ts-autoguard";

export type Content = {
	"type": string,
	"selector": string
};

export const Content = autoguard.Object.of<Content>({
	"type": autoguard.String,
	"selector": autoguard.String
});

export type MovieContent = (Content & {
	"type": "movie",
	"title": string,
	"year": number,
	"part": number,
	"imdb": string,
	"poster_url": string,
	"summary": string,
	"genres": string[],
	"actors": string[]
});

export const MovieContent = autoguard.Intersection.of(
	autoguard.Reference.of<Content>(() => Content),
	autoguard.Object.of<{
		"type": "movie",
		"title": string,
		"year": number,
		"part": number,
		"imdb": string,
		"poster_url": string,
		"summary": string,
		"genres": string[],
		"actors": string[]
	}>({
		"type": autoguard.StringLiteral.of("movie"),
		"title": autoguard.String,
		"year": autoguard.Number,
		"part": autoguard.Number,
		"imdb": autoguard.String,
		"poster_url": autoguard.String,
		"summary": autoguard.String,
		"genres": autoguard.Array.of(autoguard.String),
		"actors": autoguard.Array.of(autoguard.String)
	})
);

export type EpisodeContent = (Content & {
	"type": "episode",
	"title": string,
	"show": string,
	"season": number,
	"episode": number,
	"imdb": string,
	"imdb_show": string,
	"year": number,
	"poster_url_show"?: string,
	"summary_show": string,
	"summary": string,
	"genres_show": string[],
	"actors_show": string[]
});

export const EpisodeContent = autoguard.Intersection.of(
	autoguard.Reference.of<Content>(() => Content),
	autoguard.Object.of<{
		"type": "episode",
		"title": string,
		"show": string,
		"season": number,
		"episode": number,
		"imdb": string,
		"imdb_show": string,
		"year": number,
		"poster_url_show"?: string,
		"summary_show": string,
		"summary": string,
		"genres_show": string[],
		"actors_show": string[]
	}>({
		"type": autoguard.StringLiteral.of("episode"),
		"title": autoguard.String,
		"show": autoguard.String,
		"season": autoguard.Number,
		"episode": autoguard.Number,
		"imdb": autoguard.String,
		"imdb_show": autoguard.String,
		"year": autoguard.Number,
		"poster_url_show": autoguard.Union.of(
			autoguard.Undefined,
			autoguard.String
		),
		"summary_show": autoguard.String,
		"summary": autoguard.String,
		"genres_show": autoguard.Array.of(autoguard.String),
		"actors_show": autoguard.Array.of(autoguard.String)
	})
);

export type UnknownContent = (Content & {
	"type": "unknown"
});

export const UnknownContent = autoguard.Intersection.of(
	autoguard.Reference.of<Content>(() => Content),
	autoguard.Object.of<{
		"type": "unknown"
	}>({
		"type": autoguard.StringLiteral.of("unknown")
	})
);

export type MediaContent = (UnknownContent | MovieContent | EpisodeContent);

export const MediaContent = autoguard.Union.of(
	autoguard.Reference.of<UnknownContent>(() => UnknownContent),
	autoguard.Reference.of<MovieContent>(() => MovieContent),
	autoguard.Reference.of<EpisodeContent>(() => EpisodeContent)
);

export type MediaType = ("paldvd" | "ntscdvd" | "bluray");

export const MediaType = autoguard.Union.of(
	autoguard.StringLiteral.of("paldvd"),
	autoguard.StringLiteral.of("ntscdvd"),
	autoguard.StringLiteral.of("bluray")
);

export type Media = {
	"type": MediaType,
	"content": MediaContent[]
};

export const Media = autoguard.Object.of<Media>({
	"type": autoguard.Reference.of<MediaType>(() => MediaType),
	"content": autoguard.Array.of(autoguard.Reference.of<MediaContent>(() => MediaContent))
});

export type MediaDatabase = Record<string, undefined | Media>;

export const MediaDatabase = autoguard.Record.of(autoguard.Reference.of<Media>(() => Media));

export type Autoguard = {
	"Content": Content,
	"MovieContent": MovieContent,
	"EpisodeContent": EpisodeContent,
	"UnknownContent": UnknownContent,
	"MediaContent": MediaContent,
	"MediaType": MediaType,
	"Media": Media,
	"MediaDatabase": MediaDatabase
};

export const Autoguard = {
	"Content": Content,
	"MovieContent": MovieContent,
	"EpisodeContent": EpisodeContent,
	"UnknownContent": UnknownContent,
	"MediaContent": MediaContent,
	"MediaType": MediaType,
	"Media": Media,
	"MediaDatabase": MediaDatabase
};
