// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import { guards as autoguard } from "@joelek/ts-autoguard";

export type DeviceDetails = {
	"vendor_id": string,
	"product_id": string
};

export const DeviceDetails = autoguard.Object.of<{
	"vendor_id": string,
	"product_id": string
}>({
	"vendor_id": autoguard.String,
	"product_id": autoguard.String
});

export type Autoguard = {
	"DeviceDetails": DeviceDetails
};

export const Autoguard = {
	"DeviceDetails": DeviceDetails
};
